version: '2'

services:
  traefik:
    image: traefik
    command: --web --docker --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - traefik

networks:
  traefik:
    driver: bridge